version: '3.4'

services:
  llmplayground:
    image: llmplayground
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 Introductory.py "]
    ports:
      - 5678:5678
